export const SEARCH_INIT = 'SEARCH_INIT';
export const SEARCH_PODCASTS_SUCC = 'SEARCH_PODCASTS_SUCC';
export const SEARCH_PLAYLISTS_SUCC = 'SEARCH_PLAYLISTS_SUCC';
export const SEARCH_STATIONS_SUCC = 'SEARCH_STATIONS_SUCC';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';
