export const FAVORITES_LOADING_INIT = 'FAVORITES_LOADING_INIT';
export const FAVORITES_LOADING_SUCC = 'FAVORITES_LOADING_SUCC';
export const FAVORITES_LOADING_FAIL = 'FAVORITES_LOADING_FAIL';

export const FAVORITES_ADD_INIT = 'FAVORITES_ADD_INIT';
export const FAVORITES_DELETE_INIT = 'FAVORITES_DELETE_INIT';

export const FAVORITES_ADD_FAIL = 'FAVORITES_ADD_FAIL';
export const FAVORITES_DELETE_FAIL = 'FAVORITES_DELETE_FAIL';

export const FAVORITES_ADD_PLAYLIST_SUCC = 'FAVORITES_ADD_PLAYLIST_SUCC';
export const FAVORITES_DELETE_PLAYLIST_SUCC = 'FAVORITES_DELETE_PLAYLIST_SUCC';

export const FAVORITES_ADD_PODCAST_SUCC = 'FAVORITES_ADD_PODCAST_SUCC';
export const FAVORITES_DELETE_PODCAST_SUCC = 'FAVORITES_DELETE_PODCAST_SUCC';

export const FAVORITES_ADD_STATION_SUCC = 'FAVORITES_ADD_STATION_SUCC';
export const FAVORITES_DELETE_STATION_SUCC = 'FAVORITES_DELETE_STATION_SUCC';
