export const FAVORITES_PENDING_TRUE = 'FAVORITES_PENDING_TRUE';
export const FAVORITES_PENDING_FALSE = 'FAVORITES_PENDING_FALSE';

export const FAVORITES_LOADING_SUCC = 'FAVORITES_LOADING_SUCC';
export const FAVORITES_LOADING_FAIL = 'FAVORITES_LOADING_FAIL';

export const FAVORITES_ADD_PLAYLIST_SUCC = 'FAVORITES_ADD_PLAYLIST_SUCC';
export const FAVORITES_ADD_PODCAST_SUCC = 'FAVORITES_ADD_PODCAST_SUCC';
export const FAVORITES_ADD_STATION_SUCC = 'FAVORITES_ADD_STATION_SUCC';
export const FAVORITES_ADD_FAIL = 'FAVORITES_ADD_FAIL';

export const FAVORITES_DELETE_PLAYLIST_SUCC = 'FAVORITES_DELETE_PLAYLIST_SUCC';
export const FAVORITES_DELETE_PODCAST_SUCC = 'FAVORITES_DELETE_PODCAST_SUCC';
export const FAVORITES_DELETE_STATION_SUCC = 'FAVORITES_DELETE_STATION_SUCC';
export const FAVORITES_DELETE_FAIL = 'FAVORITES_DELETE_FAIL';
