export const SUBSCRIPTIONS_LOADING_INIT = 'SUBSCRIPTIONS_LOADING_INIT';
export const SUBSCRIPTIONS_LOADING_SUCC = 'SUBSCRIPTIONS_LOADING_SUCC';
export const SUBSCRIPTIONS_LOADING_FAIL = 'SUBSCRIPTIONS_LOADING_FAIL';
export const SUBSCRIPTIONS_UPDATE_INIT = 'SUBSCRIPTIONS_UPDATE_INIT';
export const SUBSCRIPTIONS_UPDATE_SUCC = 'SUBSCRIPTIONS_UPDATE_SUCC';
export const SUBSCRIPTIONS_UPDATE_FAIL = 'SUBSCRIPTIONS_UPDATE_FAIL';
