export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';
export const SET_USER_PLAYLISTS = 'SET_USER_PLAYLISTS';
export const PLAYLISTS_CREATE_SUCC = 'PLAYLISTS_CREATE_SUCC';
export const PLAYLISTS_DELETE_SUCC = 'PLAYLISTS_DELETE_SUCC';
